// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSubscriptionData, CreateSubscriptionResponses, DeleteSubscriptionData, DeleteSubscriptionResponses, GetFeedData, GetFeedResponses, GetSubscriptionsData, GetSubscriptionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get the user's feed
 *
 * For each subscription, the latest items are fetched from the respective RSS feed.
 */
export const getFeed = <ThrowOnError extends boolean = false>(options?: Options<GetFeedData, ThrowOnError>) => (options?.client ?? client).get<GetFeedResponses, unknown, ThrowOnError>({ url: '/api/feed', ...options });

/**
 * Get all subscriptions for the current user
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(options?: Options<GetSubscriptionsData, ThrowOnError>) => (options?.client ?? client).get<GetSubscriptionsResponses, unknown, ThrowOnError>({ url: '/api/subscriptions', ...options });

/**
 * Create a new subscription for the current user
 */
export const createSubscription = <ThrowOnError extends boolean = false>(options: Options<CreateSubscriptionData, ThrowOnError>) => (options.client ?? client).post<CreateSubscriptionResponses, unknown, ThrowOnError>({
    url: '/api/subscriptions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteSubscription = <ThrowOnError extends boolean = false>(options: Options<DeleteSubscriptionData, ThrowOnError>) => (options.client ?? client).delete<DeleteSubscriptionResponses, unknown, ThrowOnError>({ url: '/api/subscriptions/{id}', ...options });
