// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5241/' | (string & {});
};

/**
 * Application DTO representing an RSS/Atom channel/feed source.
 */
export type ChannelDto = {
    /**
     * The name of the channel. It's how people refer to your service.
     * If you have an HTML website that contains the same information as your RSS file,
     * the title of your channel should be the same as the title of your website.
     */
    title?: null | string;
    /**
     * The URL to the HTML website corresponding to the channel.
     */
    link?: null | string;
    /**
     * Phrase or sentence describing the channel.
     */
    description?: null | string;
    published?: null | string;
    items?: null | Array<ItemDto>;
    imageUrl?: null | string;
};

export type CreateSubscriptionRequest = {
    url: string;
    customTitle: null | string;
};

export type FeedResponse = {
    channels: Array<FetchChannelResult>;
};

export type FetchChannelResult = {
    success?: boolean;
    channelTitle?: null | string;
    customTitle?: null | string;
    channel?: ChannelDto;
    errorMessage?: null | string;
};

/**
 * Application DTO representing an individual RSS feed item (e.g. article).
 */
export type ItemDto = {
    title?: null | string;
    description?: null | string;
    summary?: null | string;
    author?: null | string;
    publishedAt?: null | string;
    link?: null | string;
    imageUrl?: null | string;
};

export type Subscription = {
    userId: string;
    channelUrl: string;
    channelTitle?: null | string;
    customTitle?: null | string;
    subscribedAt?: string;
    lastReadAt?: null | string;
    user?: User;
    id?: string;
};

export type SubscriptionResponse = {
    id: string;
    channelTitle: null | string;
    customTitle: null | string;
    channelUrl: string;
    subscribedAt: string;
};

export type User = {
    email: string;
    oidcSubject?: null | string;
    createdAt?: string;
    subscriptions?: Array<Subscription>;
    id?: string;
};

export type GetFeedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feed';
};

export type GetFeedResponses = {
    /**
     * OK
     */
    200: FeedResponse;
};

export type GetFeedResponse = GetFeedResponses[keyof GetFeedResponses];

export type GetSubscriptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/subscriptions';
};

export type GetSubscriptionsResponses = {
    /**
     * OK
     */
    200: Array<SubscriptionResponse>;
};

export type GetSubscriptionsResponse = GetSubscriptionsResponses[keyof GetSubscriptionsResponses];

export type CreateSubscriptionData = {
    body: CreateSubscriptionRequest;
    path?: never;
    query?: never;
    url: '/api/subscriptions';
};

export type CreateSubscriptionResponses = {
    /**
     * Created
     */
    201: Subscription;
};

export type CreateSubscriptionResponse = CreateSubscriptionResponses[keyof CreateSubscriptionResponses];

export type DeleteSubscriptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/subscriptions/{id}';
};

export type DeleteSubscriptionResponses = {
    /**
     * OK
     */
    200: unknown;
};
